spring:
  devtools:
    livereload:
      port: 35731
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?usrUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111111
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 160000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 2000
        min-idle: 5
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名
  type-aliases-package: com.yue.seckill.mapper

# Mybatis SQL打印（方法接口所在的包）
logging:
  level:
    com.xxxx.seckill.mapper: debug